default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: big_spender_development

test:
  <<: *default
  database: big_spender_test

production:
  <<: *default
  database: big_spender_production
  username: rails
  password: <%= ENV["BIG_SPENDER_DATABASE_PASSWORD"] %>
